create table edu.configs (
  id bigint generated by default as identity not null,
  name text not null,
  data jsonb null,
  is_active boolean not null default true,
  tenant_id bigint not null,
  created_by bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_by bigint null,
  updated_at timestamp with time zone null
) TABLESPACE pg_default;
