CREATE TABLE edu.questions (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  question_type_id      bigint NOT NULL,
  name                  text NULL,
  name_audio_prompt     text NULL,
  options               text NULL,
  options_audio_prompt  text NULL,
  correct_answer        text NOT NULL,
  hint                  text NULL,
  image_url             text NULL,
  sort_order            smallint NOT NULL DEFAULT 0,
  data                  jsonb NULL,
  is_active             boolean NOT NULL DEFAULT true,
  tenant_id             bigint NOT NULL,
  created_by            bigint NOT NULL,
  created_at            timestamp with time zone NOT NULL DEFAULT now(),
  updated_by            bigint NULL,
  updated_at            timestamp with time zone NULL,

  CONSTRAINT questions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_questions_question_type
    FOREIGN KEY (question_type_id)
    REFERENCES edu.question_types(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) TABLESPACE pg_default;

ALTER TABLE edu.questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY questions_tenant_isolation
  ON edu.questions
  FOR ALL
  USING (tenant_id = get_current_tenant_id());