create table edu.question_types (
  id bigint generated by default as identity not null,
  name text not null,
  icon_url text null,
  sort_order smallint not null default 0,
  data jsonb null,
  is_active boolean not null default true,
  tenant_id bigint not null,
  created_by bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_by bigint null,
  updated_at timestamp with time zone null,
  constraint question_types_pkey primary key (id)
) TABLESPACE pg_default;


ALTER TABLE edu.question_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY question_types_tenant_isolation
  ON edu.question_types
  FOR ALL
  USING (tenant_id = get_current_tenant_id());