CREATE TABLE edu.session_responses (
  id              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  session_id      bigint NOT NULL,
  student_id      bigint NOT NULL,                          -- ← added
  question_id     bigint NOT NULL,
  question_order  smallint NOT NULL,
  student_answer  text NULL,
  is_correct      boolean NULL,
  time_taken_sec  integer NULL,
  attempt_count   smallint NOT NULL DEFAULT 1,
  data            jsonb NULL,
  tenant_id       bigint NOT NULL,
  created_at      timestamp with time zone NOT NULL DEFAULT now(),
  updated_at      timestamp with time zone NULL,

  CONSTRAINT session_responses_pkey
    PRIMARY KEY (id),
  CONSTRAINT session_responses_session_fkey
    FOREIGN KEY (session_id) REFERENCES edu.sessions(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT session_responses_student_fkey
    FOREIGN KEY (student_id) REFERENCES edu.students(id)  -- ← added
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT session_responses_question_fkey
    FOREIGN KEY (question_id) REFERENCES edu.questions(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) TABLESPACE pg_default;

CREATE INDEX idx_session_responses_student
  ON edu.session_responses(student_id) TABLESPACE pg_default;

CREATE INDEX idx_session_responses_session
  ON edu.session_responses(session_id) TABLESPACE pg_default;

CREATE INDEX idx_session_responses_question
  ON edu.session_responses(question_id) TABLESPACE pg_default;
  

ALTER TABLE edu.session_responses ENABLE ROW LEVEL SECURITY;

CREATE POLICY session_responses_tenant_isolation
  ON edu.session_responses
  FOR ALL
  USING (tenant_id = get_current_tenant_id());