create table edu.sessions (
  id bigint generated by default as identity not null,
  student_id bigint not null,
  grade smallint not null,
  total_questions integer not null default 20,
  attempted integer not null default 0,
  correct integer not null default 0,
  incorrect integer not null default 0,
  skipped integer not null default 0,
  status text not null default 'IN_PROGRESS'::text,
  data jsonb null,
  metadata jsonb null,
  tenant_id bigint not null,
  created_by bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_by bigint null,
  updated_at timestamp with time zone null,
  constraint sessions_pkey primary key (id),
  constraint sessions_student_fkey foreign KEY (student_id) references edu.students (id) on update CASCADE on delete CASCADE,
  constraint sessions_status_check check (
    (
      status = any (
        array[
          'IN_PROGRESS'::text,
          'COMPLETED'::text,
          'ABANDONED'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

ALTER TABLE edu.sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY sessions_tenant_isolation
  ON edu.sessions
  FOR ALL
  USING (tenant_id = get_current_tenant_id());