create table edu.students (
  id bigint generated by default as identity not null,
  first_name text not null,
  last_name text null,
  grade smallint not null,
  dob date null,
  guardian_id bigint not null,
  teacher_id bigint null,
  school_name text null,
  avatar_url text null,
  data jsonb null,
  metadata jsonb null,
  is_active boolean not null default true,
  tenant_id bigint not null,
  created_by bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_by bigint null,
  updated_at timestamp with time zone null,
  constraint students_pkey primary key (id),
  constraint students_grade_check check (
    (
      (grade >= 1)
      and (grade <= 3)
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_students_guardian on edu.students using btree (guardian_id) TABLESPACE pg_default;

create index IF not exists idx_students_teacher on edu.students using btree (teacher_id) TABLESPACE pg_default;

create index IF not exists idx_students_grade_tenant on edu.students using btree (grade, tenant_id) TABLESPACE pg_default;

ALTER TABLE edu.students ENABLE ROW LEVEL SECURITY;

CREATE POLICY students_tenant_isolation
  ON edu.students
  FOR ALL
  USING (tenant_id = get_current_tenant_id());