create table public.tenants (
  id bigint generated by default as identity not null,
  name text not null,
  code text not null,
  data jsonb null,
  metadata jsonb null,
  access_control jsonb null,
  is_active boolean not null default true,
  created_by bigint not null,
  created_at timestamp with time zone not null,
  updated_by bigint null,
  updated_at timestamp with time zone null,
  constraint tenants_pkey primary key (id, name, code),
  constraint tenants_id_key unique (id)
) TABLESPACE pg_default;